### ISSUE TITLE
deleteProperty fails with valid input

### ISSUE THREAD

**Issue by qkennedy** [qkennedy/RentConnect#15]
when passing valid ids into deleteProperty, it crashes with the following error message:
    ReferenceError: Id is not defined

      38 |     database.open();
      39 |     return database.query(`DELETE FROM property WHERE id = ?;`,
    > 40 |                           [Id]).then( rows => {
      41 |       //Do I need to return results here?  Or does promise cover failure case
      42 |       return database.close();
      43 |     });

      at Object.deleteProperty (src/backend/propertyFactory.js:40:28)
      at Object.<anonymous> (test/unit/backend/propertyFactory.test.js:72:26)

**Comment by qkennedy** [comment]
I believe I fixed this a few commits back
