### ISSUE TITLE
Database queries are randomly throwing errors

### ISSUE THREAD

**Issue by jacob-g** [qkennedy/RentConnect#39]
```
(node:998) UnhandledPromiseRejectionWarning: Error: Cannot enqueue Quit after invoking quit.
    at Protocol._validateEnqueue (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/Protocol.js:204:16)
    at Protocol._enqueue (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/Protocol.js:139:13)
    at Protocol.quit (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/Protocol.js:92:23)
    at Connection.end (/home/jacob/Node/RentConnect/node_modules/mysql/lib/Connection.js:249:18)
    at Promise (/home/jacob/Node/RentConnect/src/backend/database.js:27:29)
    at new Promise (<anonymous>)
    at Database.close (/home/jacob/Node/RentConnect/src/backend/database.js:26:16)
    at database.query.then.rows (/home/jacob/Node/RentConnect/src/backend/userFactory.js:21:25)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
Steps to trigger
*Log in
*Refresh the page

**Comment by jacob-g** [comment]
This doesn't seem to happen every time, only on some times.

**Comment by jacob-g** [comment]
This appears to be happening in multiple different queries.
