### ISSUE TITLE
Database queries randomly failing

### ISSUE THREAD

**Issue by jacob-g** [qkennedy/RentConnect#54]
I am getting the following error code:
```
(node:1282) UnhandledPromiseRejectionWarning: Error: Cannot enqueue Quit after invoking quit.
    at Protocol._validateEnqueue (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/Protocol.js:204:16)
    at Protocol._enqueue (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/Protocol.js:139:13)
    at Protocol.quit (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/Protocol.js:92:23)
    at Connection.end (/home/jacob/Node/RentConnect/node_modules/mysql/lib/Connection.js:249:18)
    at Promise (/home/jacob/Node/RentConnect/src/backend/database.js:27:29)
    at new Promise (<anonymous>)
    at Database.close (/home/jacob/Node/RentConnect/src/backend/database.js:26:16)
    at database.query.then.rows (/home/jacob/Node/RentConnect/src/backend/MaintRequestFactory.js:63:25)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:1282) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

There does not appear to be any obvious sequence that triggers this, they just randomly fail occasionally. This has happened from a variety of different places. I remember in userFactory when I commented out all instances of `database.close()` it fixed the problem, so that may be a good temporary solution.

A list of where this has been observed so far:
* MaintRequestFactory::getCommentsByRequestId

**Comment by qkennedy** [comment]
We should not be commenting out the database.close() calls, this is a bad idea, we don't want to leave the connections open.  It seems pretty clear that this error is happening because we are calling close() on a connection that we have already closed.  I would look through the method you are calling, and see if there is a second close getting called somewhere.  It could be we use a different function, and it is doing something like open() -> open() -> close() -> close() on the same instance of database which would cause it to fail.

**Comment by jacob-g** [comment]
I am also getting this on `UserFactory::getUserById`:
```
(node:6784) UnhandledPromiseRejectionWarning: Error: Cannot enqueue Quit after invoking quit.
    at Protocol._validateEnqueue (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/Protocol.js:204:16)
    at Protocol._enqueue (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/Protocol.js:139:13)
    at Protocol.quit (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/Protocol.js:92:23)
    at Connection.end (/home/jacob/Node/RentConnect/node_modules/mysql/lib/Connection.js:249:18)
    at Promise (/home/jacob/Node/RentConnect/src/backend/database.js:27:29)
    at new Promise (<anonymous>)
    at Database.close (/home/jacob/Node/RentConnect/src/backend/database.js:26:16)
    at database.query.then.rows (/home/jacob/Node/RentConnect/src/backend/userFactory.js:24:25)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:6784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6784) UnhandledPromiseRejectionWarning: Error: Quit inactivity timeout
    at Quit.<anonymous> (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/Protocol.js:164:17)
    at emitNone (events.js:106:13)
    at Quit.emit (events.js:208:7)
    at Quit._onTimeout (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/sequences/Sequence.js:129:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
    --------------------
    at Protocol._enqueue (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.quit (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/Protocol.js:92:23)
    at Connection.end (/home/jacob/Node/RentConnect/node_modules/mysql/lib/Connection.js:249:18)
    at Promise (/home/jacob/Node/RentConnect/src/backend/database.js:27:29)
    at new Promise (<anonymous>)
    at Database.close (/home/jacob/Node/RentConnect/src/backend/database.js:26:16)
    at database.query.then.rows (/home/jacob/Node/RentConnect/src/backend/userFactory.js:24:25)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:6784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by jacob-g** [comment]
`MaintRequestFactory::getRequestById`
```
(node:7478) UnhandledPromiseRejectionWarning: Error: Quit inactivity timeout
    at Quit.<anonymous> (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/Protocol.js:164:17)
    at emitNone (events.js:106:13)
    at Quit.emit (events.js:208:7)
    at Quit._onTimeout (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/sequences/Sequence.js:129:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
    --------------------
    at Protocol._enqueue (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.quit (/home/jacob/Node/RentConnect/node_modules/mysql/lib/protocol/Protocol.js:92:23)
    at Connection.end (/home/jacob/Node/RentConnect/node_modules/mysql/lib/Connection.js:249:18)
    at Promise (/home/jacob/Node/RentConnect/src/backend/database.js:27:29)
    at new Promise (<anonymous>)
    at Database.close (/home/jacob/Node/RentConnect/src/backend/database.js:26:16)
    at database.query.then.rows (/home/jacob/Node/RentConnect/src/backend/MaintRequestFactory.js:14:25)
```

**Comment by jacob-g** [comment]
My best guess is that the things causing this error are endpoints that are often called at the same time as other endpoints, the two queries are interfering with each other.

**Comment by jacob-g** [comment]
This is also happening on the finances page, which gets both the rent history and the property information. This supports my guess above.

**Comment by jacob-g** [comment]
Sure enough, disabling loading of comments in `ViewMaintenanceRequestPage` made this stop happening on that page. The problem is concurrency, i.e. this happens:
*Request 1 opens the database
*Request 2 opens the database
*Request 1 queries
*Request 2 queries
*Request 1 closes the database
*Request 2 closes the database, but it was already closed by request 1

We need a way to handle this.
